class GameWordle {
  constructor(boardEl, keyboardEl, msgEl) {
    this.WORDS = [
      "ABACK", "ABAFT", "ABASE", "ABASH", "ABATE", "ABBES", "ABBEY", "ABBOT", "ABEAM", "ABETS", "ABHOR", "ABIDE", "ABLER", "ABLES", "ABODE", "ABORT", "ABOUT", "ABOVE", "ABUSE", "ABUTS", 
"ABUZZ", "ABYSS", "ACHED", "ACHES", "ACHOO", "ACIDS", "ACING", "ACMES", "ACNED", "ACNES", "ACORN", "ACRES", "ACRID", "ACTED", "ACTOR", "ACUTE", "ADAGE", "ADAPT", "ADDED", "ADDER", 
"ADDLE", "ADEPT", "ADIEU", "ADIOS", "ADMAN", "ADMEN", "ADMIN", "ADMIT", "ADMIX", "ADOBE", "ADOPT", "ADORE", "ADORN", "ADULT", "ADZED", "ADZES", "AEGIS", "AERIE", "AFARS", "AFFIX", 
"AFIRE", "AFOOT", "AFORE", "AFOUL", "AFTER", "AGAIN", "AGAPE", "AGARS", "AGATE", "AGAVE", "AGENT", "AGERS", "AGILE", "AGING", "AGLOW", "AGONY", "AGREE", "AGUES", "AHEAD", "AHEMS", 
"AHOYS", "AIDED", "AIDER", "AIDES", "AILED", "AIMED", "AIMER", "AIRED", "AIRER", "AISLE", "AITCH", "ALACK", "ALARM", "ALBUM", "ALDER", "ALEPH", "ALERT", "ALGAE", "ALGAL", "ALIAS", 
"ALIBI", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALKYD", "ALKYL", "ALLAY", "ALLEY", "ALLOT", "ALLOW", "ALLOY", "ALOES", "ALOFT", "ALOHA", "ALONE", "ALONG", "ALOOF", "ALOUD", "ALPHA", 
"ALTAR", "ALTER", "ALTOS", "ALUMS", "ALWAY", "AMAIN", "AMASS", "AMAZE", "AMBER", "AMBIT", "AMBLE", "AMEND", "AMENS", "AMIDE", "AMIDS", "AMIGO", "AMINO", "AMISS", "AMITY", "AMMOS", 
"AMOKS", "AMONG", "AMOUR", "AMPED", "AMPLE", "AMPLY", "AMUSE", "ANDED", "ANENT", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANGST", "ANION", "ANISE", "ANKHS", "ANKLE", "ANNAL", "ANNEX", 
"ANNOY", "ANNUL", "ANNUM", "ANODE", "ANONS", "ANTED", "ANTES", "ANTIC", "ANTIS", "ANTSY", "ANVIL", "AORTA", "APACE", "APART", "APHID", "APING", "APISH", "APPAL", "APPLE", "APPLY", 
"APRON", "APSES", "APSIS", "APTER", "APTLY", "AQUAS", "ARBOR", "ARCED", "ARDOR", "AREAL", "AREAS", "ARENA", "ARGON", "ARGOT", "ARGUE", "ARIAS", "ARISE", "ARMED", "ARMER", "ARMOR", 
"AROMA", "AROSE", "ARRAS", "ARRAY", "ARROW", "ARSES", "ARSON", "ARTSY", "ARUMS", "ASCOT", "ASHED", "ASHEN", "ASHER", "ASHES", "ASIDE", "ASKED", "ASKER", "ASKEW", "ASPEN", "ASPER", 
"ASPIC", "ASSAY", "ASSEN", "ASSES", "ASSET", "ASSOC", "ASTER", "ASTIR", "ATILT", "ATLAS", "ATOLL", "ATOMS", "ATONE", "ATRIA", "ATTAR", "ATTIC", "AUDIO", "AUDIT", "AUGER", "AUGHT", 
"AUGUR", "AUNTS", "AURAL", "AURAS", "AURIC", "AUTOS", "AUXIN", "AVAIL", "AVANT", "AVAST", "AVERS", "AVERT", "AVIAN", "AVOID", "AVOWS", "AWAIT", "AWAKE", "AWARD", "AWARE", "AWASH", 
"AWAYS", "AWFUL", "AWING", "AWNED", "AWOKE", "AXERS", "AXIAL", "AXING", "AXIOM", "AXION", "AXLES", "AXONS", "AYAHS", "AYERS", "AZURE", "BAAED", "BABEL", "BABES", "BACKS", "BACON", 
"BADEN", "BADGE", "BADLY", "BAGEL", "BAGGY", "BAHTS", "BAILS", "BAIRN", "BAITS", "BAIZE", "BAKED", "BAKER", "BAKES", "BALDS", "BALDY", "BALED", "BALER", "BALES", "BALKS", "BALKY", 
"BALLS", "BALMS", "BALMY", "BALSA", "BANAL", "BANDS", "BANDY", "BANED", "BANES", "BANGS", "BANJO", "BANKS", "BANNS", "BARBS", "BARDS", "BARED", "BARER", "BARES", "BARFS", "BARGE", 
"BARKS", "BARNS", "BARON", "BARRE", "BASAL", "BASED", "BASER", "BASES", "BASIC", "BASIL", "BASIN", "BASIS", "BASKS", "BASSO", "BASTE", "BASTS", "BATCH", "BATED", "BATER", "BATES", 
"BATHE", "BATHS", "BATIK", "BATON", "BATTY", "BAUDS", "BAULK", "BAWDS", "BAWDY", "BAWLS", "BAYED", "BAYLY", "BAYOU", "BEACH", "BEADS", "BEADY", "BEAKS", "BEAMS", "BEANS", "BEARD", 
"BEARS", "BEAST", "BEATS", "BEAUS", "BEAUT", "BEBOP", "BECKS", "BEDIM", "BEECH", "BEEFS", "BEEFY", "BEENS", "BEEPS", "BEERS", "BEERY", "BEETS", "BEFIT", "BEFOG", "BEGAN", "BEGET", 
"BEGIN", "BEGOT", "BEGUM", "BEGUN", "BEIGE", "BEING", "BELAY", "BELCH", "BELIE", "BELLE", "BELLS", "BELOW", "BELTS", "BELLY", "BEMAN", "BENCH", "BENDS", "BENTS", "BERET", "BERGS", 
"BERMS", "BERRY", "BERTH", "BERYL", "BESET", "BESOM", "BESOT", "BESTS", "BETAS", "BETEL", "BEVEL", "BEZEL", "BIBLE", "BICEP", "BIDDY", "BIDER", "BIDES", "BIDET", "BIERS", "BIFFS", 
"BIGHT", "BIGLY", "BIGOT", "BIJOU", "BIKED", "BIKER", "BIKES", "BILES", "BILGE", "BILKS", "BILLS", "BILLY", "BIMBO", "BINDS", "BINGE", "BINGO", "BIOGS", "BIPED", "BIRCH", "BIRDS", 
"BIRTH", "BISON", "BITCH", "BITER", "BITES", "BITTY", "BLABS", "BLACK", "BLADE", "BLAHS", "BLAME", "BLANC", "BLAND", "BLANK", "BLARE", "BLASE", "BLAST", "BLATS", "BLAZE", "BLEAK", 
"BLEAR", "BLEAT", "BLEED", "BLEEP", "BLEND", "BLESS", "BLIMP", "BLIND", "BLINI", "BLINK", "BLIPS", "BLISS", "BLITZ", "BLOAT", "BLOBS", "BLOCK", "BLOCS", "BLOKE", "BLOND", "BLOOD", 
"BLOOM", "BLOOP", "BLOTS", "BLOWN", "BLOWS", "BLOWY", "BLUED", "BLUER", "BLUES", "BLUET", "BLUFF", "BLUNT", "BLURB", "BLURS", "BLURT", "BLUSH", "BOARD", "BOARS", "BOAST", "BOATS", 
"BOBBY", "BOCKS", "BODED", "BODES", "BOFFO", "BOGEY", "BOGON", "BOGUS", "BOGGY", "BOILS", "BOINK", "BOLAS", "BOLDS", "BOLES", "BOLLS", "BOLOS", "BOLTS", "BOLUS", "BOMBS", "BONDS", 
"BONED", "BONER", "BONES", "BONGO", "BONGS", "BONUS", "BONNY", "BOOBS", "BOOBY", "BOOED", "BOOKS", "BOOMS", "BOONS", "BOORS", "BOOST", "BOOTH", "BOOTS", "BOOTY", "BOOZE", "BOOZY", 
"BORAX", "BORED", "BORER", "BORES", "BORIC", "BORNE", "BORON", "BOSOM", "BOSON", "BOSSY", "BOSUN", "BOTCH", "BOTHY", "BOUGH", "BOUND", "BOUTS", "BOWED", "BOWEL", "BOWEN", "BOWER", 
"BOWIE", "BOWLS", "BOXED", "BOXEN", "BOXER", "BOXES", "BOYER", "BOZOS", "BRACE", "BRACT", "BRADS", "BRAES", "BRAGS", "BRAID", "BRAIN", "BRAKE", "BRAND", "BRANS", "BRASH", "BRASS", 
"BRATS", "BRAVE", "BRAVO", "BRAWL", "BRAWN", "BRAYS", "BRAZE", "BREAD", "BREAK", "BREAM", "BREED", "BREVE", "BREWS", "BRIBE", "BRICK", "BRIDE", "BRIEF", "BRIER", "BRIGS", "BRIMS", 
"BRINE", "BRING", "BRINK", "BRINY", "BRISK", "BROAD", "BROIL", "BROKE", "BRONC", "BROOD", "BROOK", "BROOM", "BROTH", "BROWN", "BROWS", "BRUIN", "BRUIT", "BRUNT", "BRUSH", "BRUTE", 
"BUCKS", "BUDDY", "BUDGE", "BUFFS", "BUGLE", "BUGGY", "BUILD", "BUILT", "BULBS", "BULGE", "BULGY", "BULKS", "BULKY", "BULLS", "BULLY", "BUMPS", "BUMPY", "BUNCH", "BUNCO", "BUNGS", 
"BUNKS", "BUNTS", "BUNNY", "BUOYS", "BURBS", "BURGH", "BURGS", "BURLS", "BURLY", "BURNS", "BURNT", "BURPS", "BURRO", "BURRS", "BURSA", "BURST", "BUSBY", "BUSED", "BUSES", "BUSHY", 
"BUSTS", "BUSTY", "BUTCH", "BUTTE", "BUTTS", "BUTYL", "BUXOM", "BUYER", "BUZZY", "BYERS", "BYLAW", "BYRES", "BYTES", "BYWAY", "CABAL", "CABER", "CABIN", "CABLE", "CACAO", "CACHE", 
"CACTI", "CADDY", "CADET", "CADGE", "CADRE", "CAFES", "CAGED", "CAGER", "CAGES", "CAGEY", "CAIRN", "CAKED", "CAKES", "CALLA", "CALLS", "CALMS", "CALVE", "CALYX", "CAMEL", "CAMEO", 
"CAMES", "CAMPS", "CAMPY", "CANAL", "CANDY", "CANED", "CANER", "CANES", "CANOE", "CANON", "CANST", "CANTO", "CANTS", "CANNY", "CAPED", "CAPER", "CAPES", "CAPON", "CAPOS", "CARAT", 
"CARDS", "CARED", "CARER", "CARES", "CARET", "CARGO", "CARNY", "CAROB", "CAROL", "CAROM", "CARPI", "CARPS", "CARRY", "CARTE", "CARTS", "CARVE", "CASED", "CASES", "CASKS", "CASTE", 
"CASTS", "CATCH", "CATER", "CATTY", "CAULK", "CAUSE", "CAVED", "CAVER", "CAVES", "CAVIL", "CAWED", "CEASE", "CECAL", "CECUM", "CEDAR", "CEDED", "CEDER", "CEDES", "CELLO", "CELLS", 
"CENTS", "CERTS", "CHADS", "CHAFE", "CHAFF", "CHAIN", "CHAIR", "CHALK", "CHAMP", "CHANT", "CHAOS", "CHAPS", "CHARD", "CHARM", "CHARS", "CHART", "CHARY", "CHASE", "CHASM", "CHATS", 
"CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEEP", "CHEER", "CHEFS", "CHEMO", "CHERT", "CHESS", "CHEST", "CHEWS", "CHEWY", "CHICK", "CHICS", "CHIDE", "CHIEF", "CHILD", "CHILI", "CHILL", 
"CHIME", "CHIMP", "CHINA", "CHINE", "CHINK", "CHINO", "CHINS", "CHIPS", "CHIRP", "CHITS", "CHIVE", "CHOCK", "CHOIR", "CHOKE", "CHOMP", "CHOPS", "CHORD", "CHORE", "CHOSE", "CHOWS", 
"CHUBS", "CHUCK", "CHUFF", "CHUGS", "CHUMP", "CHUMS", "CHUNK", "CHURL", "CHURN", "CHUTE", "CHYME", "CIAOS", "CIDER", "CIGAR", "CILIA", "CINCH", "CIRCA", "CIRRI", "CITED", "CITES", 
"CIVET", "CIVIC", "CIVIL", "CLACK", "CLADS", "CLAIM", "CLAMP", "CLAMS", "CLANG", "CLANK", "CLANS", "CLAPS", "CLASH", "CLASP", "CLASS", "CLAVE", "CLAWS", "CLAYS", "CLEAN", "CLEAR", 
"CLEAT", "CLEFS", "CLEFT", "CLERK", "CLEWS", "CLICK", "CLIFF", "CLIMB", "CLIME", "CLING", "CLINK", "CLIPS", "CLOAK", "CLOCK", "CLODS", "CLOGS", "CLOMP", "CLONE", "CLONK", "CLOPS", 
"CLOSE", "CLOTH", "CLOTS", "CLOUD", "CLOUT", "CLOVE", "CLOWN", "CLOYS", "CLUBS", "CLUCK", "CLUED", "CLUES", "CLUMP", "CLUNG", "CLUNK", "CLVII", "CLXII", "CLXIV", "CLXIX", "CLXVI", 
"COACH", "COALS", "COAST", "COATS", "COBLE", "COBRA", "COCAS", "COCCI", "COCKS", "COCKY", "COCOA", "COCOS", "CODAS", "CODED", "CODER", "CODES", "CODEX", "COEDS", "COHOS", "COIFS", 
"COILS", "COINS", "COKED", "COKES", "COLAS", "COLDS", "COLED", "COLIC", "COLON", "COLOR", "COLTS", "COMAE", "COMAS", "COMBO", "COMBS", "COMER", "COMES", "COMET", "COMFY", "COMIC", 
"COMMA", "COMPO", "COMPS", "CONCH", "CONDO", "CONED", "CONES", "CONGA", "CONIC", "CONKS", "CONTD", "COOED", "COOKS", "COOLS", "COONS", "COOPS", "COOTS", "COPAY", "COPED", "COPER", 
"COPES", "COPRA", "COPSE", "CORAL", "CORDS", "CORED", "CORER", "CORES", "CORGI", "CORKS", "CORMS", "CORNS", "CORNY", "CORPS", "COSED", "COSES", "COSTS", "COTED", "COTES", "COUCH", 
"COUGH", "COULD", "COUNT", "COUPE", "COUPS", "COURT", "COVED", "COVEN", "COVER", "COVES", "COVET", "COVEY", "COWED", "COWER", "COWLS", "COXED", "COXES", "COYED", "COYER", "COYLY", 
"COYPU", "COZEN", "CRABS", "CRACK", "CRAFT", "CRAGS", "CRAMP", "CRAMS", "CRANE", "CRANK", "CRAPE", "CRAPS", "CRASH", "CRASS", "CRATE", "CRAVE", "CRAWL", "CRAWS", "CRAYS", "CRAZE", 
"CRAZY", "CREAK", "CREAM", "CREDO", "CREED", "CREEK", "CREEL", "CREEP", "CREME", "CREPE", "CREPT", "CRESS", "CREST", "CREWS", "CRIBS", "CRICK", "CRIED", "CRIER", "CRIES", "CRIME", 
"CRIMP", "CRISP", "CRISS", "CROAK", "CROCK", "CROFT", "CRONE", "CRONY", "CROOK", "CROON", "CROPS", "CROSS", "CROUP", "CROWD", "CROWN", "CROWS", "CRUDE", "CRUDS", "CRUEL", "CRUET", 
"CRUFT", "CRUMB", "CRUMP", "CRUSE", "CRUSH", "CRUST", "CRYPT", "CUBED", "CUBER", "CUBES", "CUBIC", "CUBIT", "CUFFS", "CUING", "CULLS", "CULPA", "CULTS", "CUMIN", "CUNTS", "CUPID", 
"CURBS", "CURDS", "CURED", "CURER", "CURES", "CURFS", "CURIA", "CURIE", "CURIO", "CURLS", "CURLY", "CURRY", "CURSE", "CURVE", "CURVY", "CUSHY", "CUSPS", "CUTER", "CUTES", "CUTIE", 
"CUTUP", "CYANS", "CYCLE", "CYDER", "CYNIC", "CYSTS", "CZARS", "DACES", "DACHA", "DADDY", "DAFFY", "DAILY", "DAIRY", "DAISY", "DALES", "DALLY", "DAMED", "DAMES", "DAMNS", "DAMPS", 
"DANCE", "DANDY", "DANGS", "DARED", "DARER", "DARES", "DARKS", "DARNS", "DARTS", "DATED", "DATER", "DATES", "DATUM", "DAUBS", "DAUNT", "DAVIT", "DAWNS", "DAZED", "DAZES", "DDING", 
"DEALS", "DEALT", "DEANS", "DEARS", "DEARY", "DEATH", "DEBAR", "DEBIT", "DEBTS", "DEBUG", "DEBUT", "DECAF", "DECAL", "DECAY", "DECKS", "DECOR", "DECOY", "DECRY", "DEEDS", "DEEMS", 
"DEEPS", "DEERS", "DEFER", "DEFIS", "DEFOG", "DEGAS", "DEGUM", "DEICE", "DEIFY", "DEIGN", "DEISM", "DEIST", "DEITY", "DELAY", "DELFS", "DELFT", "DELIS", "DELLS", "DELTA", "DELVE", 
"DEMIT", "DEMON", "DEMOS", "DEMUR", "DENIM", "DENSE", "DENTS", "DEPOT", "DEPTH", "DERBY", "DERES", "DESKS", "DETER", "DETOX", "DEUCE", "DEVIL", "DEWAR", "DEWED", "DEXES", "DHOTI", 
"DHOWS", "DIALS", "DIARY", "DICED", "DICER", "DICES", "DICEY", "DICKS", "DICTA", "DIDST", "DIETS", "DIFFS", "DIGIT", "DIKED", "DIKER", "DIKES", "DILLS", "DILLY", "DIMER", "DIMES", 
"DIMLY", "DINAR", "DINED", "DINER", "DINES", "DINGO", "DINGS", "DINGY", "DINKY", "DINTS", "DIODE", "DIPPY", "DIRER", "DIRGE", "DIRKS", "DIRTS", "DIRTY", "DISCO", "DISKS", "DITCH", 
"DITSY", "DITTO", "DITTY", "DIVAN", "DIVAS", "DIVED", "DIVER", "DIVES", "DIVOT", "DIVVY", "DIZZY", "DOCKS", "DODGE", "DODGY", "DODOS", "DOERS", "DOEST", "DOFFS", "DOGES", "DOGIE", 
"DOGMA", "DOGGY", "DOILY", "DOING", "DOLED", "DOLES", "DOLLS", "DOLOR", "DOLTS", "DOLLY", "DOMED", "DOMES", "DONAS", "DONGS", "DONOR", "DONUT", "DOOMS", "DOORS", "DOPAS", "DOPED", 
"DOPER", "DOPES", "DOPEY", "DORKS", "DORKY", "DORMS", "DOSED", "DOSES", "DOTED", "DOTER", "DOTES", "DOTTY", "DOUBT", "DOUGH", "DOUSE", "DOVER", "DOVES", "DOWDY", "DOWEL", "DOWER", 
"DOWNS", "DOWNY", "DOWRY", "DOWSE", "DOYEN", "DOZED", "DOZEN", "DOZER", "DOZES", "DRABS", "DRAFT", "DRAGS", "DRAIN", "DRAKE", "DRAMA", "DRAMS", "DRANK", "DRAPE", "DRATS", "DRAWL", 
"DRAWN", "DRAWS", "DRAYS", "DREAD", "DREAM", "DREAR", "DREES", "DREGS", "DRESS", "DRIBS", "DRIED", "DRIER", "DRIES", "DRIFT", "DRILL", "DRINK", "DRIPS", "DRIVE", "DROID", "DROLL", 
"DRONE", "DROOL", "DROOP", "DROPS", "DROSS", "DROVE", "DROWN", "DRUBS", "DRUGS", "DRUID", "DRUMS", "DRUNK", "DRUPE", "DRYAD", "DRYER", "DRYLY", "DUALS", "DUCAL", "DUCAT", "DUCHY", 
"DUCKS", "DUCKY", "DUCTS", "DUDED", "DUDES", "DUELS", "DUETS", "DUFFS", "DUKED", "DUKES", "DULLS", "DULLY", "DUMBS", "DUMMY", "DUMPS", "DUMPY", "DUNCE", "DUNES", "DUNGS", "DUNKS", 
"DUNNO", "DUPED", "DUPER", "DUPES", "DUPLE", "DURST", "DURUM", "DUSKS", "DUSKY", "DUSTS", "DUSTY", "DUTCH", "DUVET", "DUXES", "DWARF", "DWEEB", "DWELL", "DWELT", "DYADS", "DYERS", 
"DYING", "EAGER", "EAGLE", "EARED", "EARLS", "EARLY", "EARNS", "EARTH", "EASED", "EASEL", "EASER", "EASES", "EASTS", "EATEN", "EATER", "EAVES", "EBBED", "EBONY", "ECHOS", "ECLAT", 
"ECRUS", "EDEMA", "EDGED", "EDGER", "EDGES", "EDICT", "EDIFY", "EDITS", "EDUCE", "EERIE", "EGGED", "EGGER", "EGRET", "EIDER", "EIGHT", "EJECT", "EKING", "ELAND", "ELANS", "ELATE", 
"ELBOW", "ELDER", "ELECT", "ELEGY", "ELFIN", "ELIDE", "ELITE", "ELMER", "ELOPE", "ELUDE", "ELUTE", "ELVEN", "ELVER", "ELVES", "EMACS", "EMAIL", "EMBED", "EMBER", "EMCEE", "EMEND", 
"EMERY", "EMIRS", "EMITS", "EMOTE", "EMPTY", "ENACT", "ENDED", "ENDER", "ENDOW", "ENDUE", "ENEMA", "ENEMY", "ENJOY", "ENNUI", "ENROL", "ENSUE", "ENTER", "ENTRY", "ENVOY", "EPEES", 
"EPICS", "EPOCH", "EPOXY", "EQUAL", "EQUIP", "EQUIV", "ERASE", "ERECT", "ERGOT", "ERODE", "ERRED", "ERROR", "ERUCT", "ERUPT", "ESSAY", "ESTER", "ETHER", "ETHIC", "ETHOS", "ETHYL", 
"ÉTUDE", "EUROS", "EVADE", "EVENS", "EVENT", "EVERY", "EVICT", "EVILS", "EVOKE", "EWERS", "EXACT", "EXALT", "EXAMS", "EXCEL", "EXCLS", "EXECS", "EXERT", "EXILE", "EXIST", "EXITS", 
"EXPEL", "EXPOS", "EXTOL", "EXTRA", "EXUDE", "EXULT", "EXURB", "EYERS", "EYING", "EYRES", "FABLE", "FACED", "FACER", "FACES", "FACET", "FACTO", "FACTS", "FADED", "FADER", "FADES", 
"FAGOT", "FAILS", "FAINS", "FAINT", "FAIRS", "FAIRY", "FAITH", "FAKED", "FAKER", "FAKES", "FAKIR", "FALLS", "FALSE", "FAMED", "FAMES", "FANCY", "FANGS", "FANNY", "FARAD", "FARCE", 
"FARED", "FARER", "FARES", "FARMS", "FAROS", "FARTS", "FASTS", "FATAL", "FATED", "FATES", "FATLY", "FATSO", "FATWA", "FATTY", "FAULT", "FAUNA", "FAUNS", "FAVOR", "FAWNS", "FAXED", 
"FAXES", "FAYED", "FAYER", "FAYRE", "FAZED", "FAZES", "FEARS", "FEAST", "FEATS", "FECAL", "FECES", "FEEDS", "FEELS", "FEIGN", "FEINT", "FELLA", "FELLS", "FELON", "FELTS", "FEMME", 
"FEMUR", "FENCE", "FENDS", "FERAL", "FERNS", "FERNY", "FERRO", "FERRY", "FESTS", "FETAL", "FETAS", "FETCH", "FETED", "FETES", "FETID", "FETUS", "FEUDS", "FEVER", "FEWER", "FEYER", 
"FIATS", "FIBER", "FIBRE", "FICES", "FICHE", "FICHU", "FICOS", "FICUS", "FIEFS", "FIELD", "FIEND", "FIERY", "FIFED", "FIFER", "FIFES", "FIFTH", "FIFTY", "FIGHT", "FILCH", "FILED", 
"FILER", "FILES", "FILLS", "FILMS", "FILMY", "FILTH", "FILLY", "FINAL", "FINCH", "FINDS", "FINED", "FINER", "FINES", "FINIS", "FINKS", "FINNY", "FIRED", "FIRER", "FIRES", "FIRMS", 
"FIRST", "FIRTH", "FISHY", "FISTS", "FITLY", "FIVER", "FIVES", "FIXED", "FIXER", "FIXES", "FIZZY", "FJORD", "FLABS", "FLACK", "FLAGS", "FLAIL", "FLAIR", "FLAKE", "FLAKS", "FLAKY", 
"FLAME", "FLANK", "FLANS", "FLAPS", "FLARE", "FLASH", "FLASK", "FLATS", "FLAWS", "FLAYS", "FLEAS", "FLECK", "FLEER", "FLEES", "FLEET", "FLESH", "FLEWS", "FLICK", "FLIED", "FLIER", 
"FLIES", "FLING", "FLINT", "FLIPS", "FLIRT", "FLITS", "FLOAT", "FLOCK", "FLOES", "FLOGS", "FLOOD", "FLOOR", "FLOPS", "FLORA", "FLOSS", "FLOUR", "FLOUT", "FLOWN", "FLOWS", "FLUBS", 
"FLUES", "FLUFF", "FLUID", "FLUKE", "FLUKY", "FLUME", "FLUNG", "FLUNK", "FLUSH", "FLUTE", "FLYBY", "FOALS", "FOAMS", "FOAMY", "FOCAL", "FOCUS", "FOGEY", "FOGGY", "FOILS", "FOIST", 
"FOLDS", "FOLIO", "FOLKS", "FOLLY", "FONDS", "FONTS", "FOODS", "FOOLS", "FOOTS", "FORAY", "FORCE", "FORDS", "FORES", "FORGE", "FORGO", "FORKS", "FORMS", "FORTE", "FORTH", "FORTS", 
"FORTY", "FORUM", "FOULS", "FOUND", "FOUNT", "FOURS", "FOVEA", "FOWLS", "FOXED", "FOXES", "FOYER", "FRAGS", "FRAIL", "FRAME", "FRANC", "FRANK", "FRATS", "FRAUD", "FRAYS", "FREAK", 
"FREED", "FREER", "FREES", "FREON", "FRESH", "FRETS", "FRIAR", "FRIED", "FRIES", "FRIGS", "FRILL", "FRISK", "FRITZ", "FRIZZ", "FROCK", "FROGS", "FROND", "FRONT", "FROSH", "FROST", 
"FROTH", "FROWN", "FROZE", "FRUIT", "FRUMP", "FRYER", "FTPER", "FUCKS", "FUDGE", "FUELS", "FUGAL", "FUGUE", "FULLS", "FULLY", "FUMED", "FUMES", "FUNDS", "FUNGI", "FUNKS", "FUNKY", 
"FUNNY", "FURLS", "FUROR", "FURRY", "FURZE", "FUSED", "FUSEE", "FUSES", "FUSSY", "FUSTY", "FUTON", "FUZZY", "GABBY", "GABLE", "GAFFE", "GAFFS", "GAGED", "GAGER", "GAGES", "GAILY", 
"GAINS", "GAITS", "GALAS", "GALEN", "GALES", "GALLS", "GAMED", "GAMER", "GAMES", "GAMIN", "GAMMA", "GAMUT", "GANGS", "GAOLS", "GAPED", "GAPER", "GAPES", "GARBS", "GASES", "GASPS", 
"GASSY", "GATED", "GATES", "GATOR", "GAUDY", "GAUGE", "GAUNT", "GAUSS", "GAUZE", "GAUZY", "GAVEL", "GAWKS", "GAWKY", "GAYER", "GAZED", "GAZER", "GAZES", "GEARS", "GECKO", "GEEKS", 
"GEEKY", "GEESE", "GEEST", "GELDS", "GELID", "GENES", "GENIE", "GENII", "GENRE", "GENTS", "GENUS", "GEODE", "GERMS", "GETUP", "GHATS", "GHOST", "GHOUL", "GIANT", "GIBED", "GIBER", 
"GIBES", "GIDDY", "GIFTS", "GILDS", "GILLS", "GILTS", "GIMME", "GIMPS", "GIMPY", "GIRDS", "GIRLS", "GIRTH", "GIRTS", "GISTS", "GIVEN", "GIVER", "GIVES", "GLACE", "GLADE", "GLADS", 
"GLAND", "GLANS", "GLARE", "GLASS", "GLAZE", "GLEAM", "GLEAN", "GLEED", "GLEES", "GLENS", "GLIDE", "GLINT", "GLITZ", "GLOAT", "GLOBE", "GLOBS", "GLOOM", "GLOPS", "GLORY", "GLOSS", 
"GLOVE", "GLOWS", "GLUED", "GLUER", "GLUES", "GLUEY", "GLUMS", "GLUON", "GLUTS", "GLYPH", "GNARL", "GNASH", "GNATS", "GNAWS", "GNOME", "GOADS", "GOALS", "GOATS", "GODLY", "GOERS", 
"GOFER", "GOING", "GOLDS", "GOLFS", "GOLLY", "GONAD", "GONER", "GONGS", "GONKS", "GONNA", "GONZO", "GOODS", "GOODY", "GOOEY", "GOOFS", "GOOFY", "GOOKS", "GOONS", "GOOPS", "GOOSE", 
"GORED", "GORES", "GORGE", "GORPS", "GORSE", "GOTTA", "GOUGE", "GOURD", "GOUTS", "GOUTY", "GOWNS", "GRABS", "GRACE", "GRADE", "GRADS", "GRAFT", "GRAIL", "GRAIN", "GRAMS", "GRAND", 
"GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS", "GRATE", "GRAVE", "GRAVY", "GRAYS", "GRAZE", "GREAT", "GREBE", "GREED", "GREEN", "GREET", "GREPS", "GREYS", "GRIDS", "GRIEF", "GRILL", 
"GRIME", "GRIMY", "GRIND", "GRINS", "GRIPE", "GRIPS", "GRIST", "GRITS", "GROAN", "GROAT", "GROGS", "GROIN", "GROKS", "GROOM", "GROPE", "GROSS", "GROUP", "GROUT", "GROVE", "GROWL", 
"GROWN", "GROWS", "GRUBS", "GRUEL", "GRUES", "GRUFF", "GRUMP", "GRUNT", "GUANO", "GUARD", "GUAVA", "GUESS", "GUEST", "GUFFS", "GUIDE", "GUILD", "GUILE", "GUILT", "GUISE", "GULAG", 
"GULCH", "GULFS", "GULLS", "GULPS", "GULLY", "GUMBO", "GUMMY", "GUNKS", "GUNKY", "GUNNY", "GUPPY", "GURUS", "GUSHY", "GUSSY", "GUSTO", "GUSTS", "GUSTY", "GUTSY", "GUTTY", "GUYED", 
"GUYER", "GYBED", "GYBES", "GYPSY", "GYROS", "GYVED", "GYVES", "HABIT", "HACKS", "HADED", "HADES", "HADST", "HAFTS", "HAGEN", "HAIKU", "HAILS", "HAIRS", "HAIRY", "HAJJI", "HAKES", 
"HALAL", "HALED", "HALER", "HALES", "HALLO", "HALLS", "HALON", "HALOS", "HALTS", "HALVE", "HAMMY", "HANDS", "HANDY", "HANGS", "HANKS", "HAPLY", "HAPPY", "HARDS", "HARDY", "HARED", 
"HAREM", "HARES", "HARKS", "HARMS", "HARPS", "HARPY", "HARRY", "HARSH", "HARTS", "HASPS", "HASTE", "HASTY", "HATCH", "HATED", "HATER", "HATES", "HAULS", "HAUNT", "HAVEN", "HAVER", 
"HAVES", "HAVOC", "HAWED", "HAWKS", "HAYED", "HAYER", "HAZED", "HAZEL", "HAZER", "HAZES", "HDQRS", "HEADS", "HEADY", "HEALS", "HEAPS", "HEARD", "HEARS", "HEART", "HEATH", "HEATS", 
"HEAVE", "HEAVY", "HECKS", "HEDGE", "HEEDS", "HEELS", "HEFTS", "HEFTY", "HEIRS", "HEIST", "HELIX", "HELLO", "HELLS", "HELMS", "HELOT", "HELPS", "HELVE", "HEMES", "HEMPS", "HENCE", 
"HENGE", "HENNA", "HENRY", "HERBS", "HERDS", "HERES", "HERON", "HERTZ", "HEWED", "HEWER", "HEXED", "HEXER", "HEXES", "HICKS", "HIDED", "HIDER", "HIDES", "HIGHS", "HIGHT", "HIKED", 
"HIKER", "HIKES", "HILLS", "HILTS", "HILLY", "HINDS", "HINGE", "HINGS", "HINTS", "HIPPO", "HIRED", "HIRER", "HIRES", "HISTS", "HITCH", "HIVED", "HIVES", "HOARD", "HOARY", "HOBBY", 
"HOBOS", "HOCKS", "HODGE", "HOERS", "HOGAN", "HOIST", "HOKED", "HOKES", "HOKEY", "HOKUM", "HOLDS", "HOLED", "HOLES", "HOLEY", "HOLLY", "HOMED", "HOMER", "HOMES", "HOMEY", "HOMOS", 
"HONED", "HONER", "HONES", "HONEY", "HONKS", "HONKY", "HONOR", "HOOCH", "HOODS", "HOOEY", "HOOFS", "HOOKS", "HOOKY", "HOOPS", "HOOTS", "HOPED", "HOPER", "HOPES", "HORAS", "HORDE", 
"HORNS", "HORNY", "HORSE", "HOSED", "HOSES", "HOSTS", "HOTEL", "HOTLY", "HOUGH", "HOUND", "HOURI", "HOURS", "HOUSE", "HOVEL", "HOVER", "HOWDY", "HOWLS", "HUBBA", "HUBBY", "HUFFS", 
"HUFFY", "HUGER", "HULAS", "HULKS", "HULLO", "HULLS", "HUMAN", "HUMID", "HUMOR", "HUMPH", "HUMPS", "HUMUS", "HUNCH", "HUNKS", "HUNKY", "HUNTS", "HURLS", "HURRY", "HURTS", "HUSKS", 
"HUSKY", "HUSSY", "HUTCH", "HYDRA", "HYDRO", "HYENA", "HYING", "HYMEN", "HYMNS", "HYPED", "HYPER", "HYPES", "HYPOS", "IAMBI", "IAMBS", "ICIER", "ICILY", "ICING", "ICONS", "ICTUS", 
"IDEAL", "IDEAS", "IDIOM", "IDIOT", "IDLED", "IDLER", "IDLES", "IDOLS", "IDYLL", "IGLOO", "ILEUM", "ILIAC", "ILIUM", "ILLUS", "IMAGE", "IMAGO", "IMAMS", "IMBUE", "IMPED", "IMPEL", 
"IMPER", "IMPLY", "INANE", "INAPT", "INCED", "INCUR", "INDEX", "INEPT", "INERT", "INFER", "INFIX", "INFOS", "INFRA", "INGOT", "INION", "INKED", "INKER", "INLAY", "INLET", "INNED", 
"INNER", "INPUT", "INSET", "INSTR", "INTER", "INTRA", "INTRO", "INURE", "IOCTL", "IONIC", "IOTAS", "IRATE", "IRIDS", "IRING", "IRKED", "IRONS", "IRONY", "ISLED", "ISLES", "ISLET", 
"ISSUE", "ITCHY", "ITEMS", "IVIED", "IVIES", "IVORY", "JABOT", "JACKS", "JADED", "JADES", "JAILS", "JAMBS", "JAPAN", "JAPED", "JAPES", "JATOS", "JAUNT", "JAVAS", "JAWED", "JAZZY", 
"JEANS", "JEEPS", "JEERS", "JELLO", "JELLS", "JELLY", "JEMMY", "JENNY", "JERKS", "JERKY", "JERRY", "JESTS", "JETTY", "JEWEL", "JIBED", "JIBES", "JIFFS", "JIFFY", "JIHAD", "JILTS", 
"JIMMY", "JINGO", "JINNS", "JIVED", "JIVES", "JOCKS", "JOHNS", "JOINS", "JOINT", "JOIST", "JOKED", "JOKER", "JOKES", "JOKEY", "JOLTS", "JOLLY", "JOULE", "JOUST", "JOWLS", "JOWLY", 
"JOYED", "JUDGE", "JUDOS", "JUICE", "JUICY", "JUKES", "JULEP", "JUMBO", "JUMPS", "JUMPY", "JUNCO", "JUNKS", "JUNTA", "JUROR", "JUSTS", "JUTES", "KABOB", "KALES", "KAPOK", "KAPPA", 
"KAPUT", "KARAT", "KARMA", "KARTS", "KAYAK", "KAYOS", "KAZOO", "KEBAB", "KEELS", "KEENS", "KEEPS", "KELPS", "KENOS", "KEPIS", "KERBS", "KETCH", "KEYED", "KHAKI", "KHANS", "KICKS", 
"KICKY", "KIDDO", "KILLS", "KILNS", "KILOS", "KILTS", "KINDA", "KINDS", "KINES", "KINGS", "KINKS", "KINKY", "KIOSK", "KIRKS", "KITED", "KITER", "KITES", "KITHS", "KITTY", "KIWIS", 
"KLUGE", "KLUTZ", "KNACK", "KNAVE", "KNEAD", "KNEED", "KNEEL", "KNEES", "KNELL", "KNELT", "KNICK", "KNIFE", "KNISH", "KNITS", "KNOBS", "KNOCK", "KNOLL", "KNOTS", "KNOWN", "KNOWS", 
"KNURL", "KOALA", "KOANS", "KOLAS", "KOOKS", "KOOKY", "KRAAL", "KRAFT", "KRAUT", "KRILL", "KRÓNA", "KRONE", "KUDOS", "KUDZU", "LABEL", "LABIA", "LABOR", "LACED", "LACER", "LACES", 
"LACKS", "LADED", "LADEN", "LADES", "LADLE", "LAGER", "LAING", "LAIRD", "LAIRS", "LAITY", "LAKED", "LAKER", "LAKES", "LAMAS", "LAMBS", "LAMED", "LAMER", "LAMES", "LAMPS", "LANAI", 
"LANCE", "LANDS", "LANES", "LANKY", "LAPEL", "LAPIN", "LAPSE", "LARCH", "LARDS", "LARDY", "LARGE", "LARGO", "LARKS", "LARVA", "LASED", "LASER", "LASES", "LASSO", "LASTS", "LATCH", 
"LATED", "LATER", "LATEX", "LATHE", "LATHS", "LATTE", "LAUDS", "LAUGH", "LAURA", "LAVAS", "LAVED", "LAVES", "LAWED", "LAWNS", "LAXER", "LAXES", "LAXLY", "LAYER", "LAYUP", "LAZED", 
"LAZES", "LEACH", "LEADS", "LEAFS", "LEAFY", "LEAKS", "LEAKY", "LEANS", "LEAPS", "LEARN", "LEASE", "LEASH", "LEAST", "LEAVE", "LEDGE", "LEECH", "LEEKS", "LEERS", "LEERY", "LEFTS", 
"LEFTY", "LEGAL", "LEGIT", "LEGGY", "LEMMA", "LEMME", "LEMON", "LEMUR", "LENDS", "LENTO", "LEPER", "LEPTA", "LETUP", "LEVEE", "LEVEL", "LEVER", "LEWIS", "LEXER", "LIARS", "LIBEL", 
"LICIT", "LICKS", "LIDOS", "LIEFS", "LIEGE", "LIENS", "LIEUS", "LIEUT", "LIFER", "LIFTS", "LIGHT", "LIKED", "LIKEN", "LIKER", "LIKES", "LILAC", "LILTS", "LIMBO", "LIMBS", "LIMED", 
"LIMES", "LIMIT", "LIMNS", "LIMOS", "LIMPS", "LINED", "LINEN", "LINER", "LINES", "LINGO", "LINGS", "LINKS", "LINTS", "LINTY", "LIONS", "LIPID", "LIPPY", "LISLE", "LISPS", "LISTS", 
"LITER", "LITES", "LITHE", "LITRE", "LIVED", "LIVEN", "LIVER", "LIVES", "LIVID", "LLAMA", "LLANO", "LOADS", "LOAFS", "LOAMS", "LOAMY", "LOANS", "LOATH", "LOBAR", "LOBBY", "LOBED", 
"LOBES", "LOCAL", "LOCHS", "LOCKS", "LOCOS", "LOCUS", "LODES", "LODGE", "LOFTS", "LOFTY", "LOGES", "LOGIC", "LOGIN", "LOGOS", "LOINS", "LOLLS", "LOLLY", "LONER", "LONGS", "LOOKS", 
"LOOMS", "LOONS", "LOONY", "LOOPS", "LOOPY", "LOOSE", "LOOTS", "LOPED", "LOPER", "LOPES", "LORDS", "LORES", "LORIS", "LORRY", "LOSER", "LOSES", "LOSSY", "LOTTO", "LOTUS", "LOURS", 
"LOUSE", "LOUSY", "LOUTS", "LOVED", "LOVER", "LOVES", "LOWED", "LOWER", "LOWLY", "LOXED", "LOXES", "LOYAL", "LUAUS", "LUBED", "LUBES", "LUCID", "LUCKS", "LUCKY", "LUCRE", "LUFFS", 
"LUGER", "LULLS", "LUMEN", "LUMPS", "LUMPY", "LUNAR", "LUNCH", "LUNGE", "LUNGS", "LUPIN", "LUPUS", "LURCH", "LURED", "LURER", "LURES", "LUREX", "LURID", "LURKS", "LUSTS", "LUSTY", 
"LUTED", "LUTES", "LUXES", "LXVII", "LYING", "LYMPH", "LYNCH", "LYRES", "LYRIC", "MACAW", "MACED", "MACER", "MACES", "MACHO", "MACRO", "MADAM", "MADLY", "MAFIA", "MAGIC", "MAGMA", 
"MAIDS", "MAIER", "MAILS", "MAIMS", "MAINS", "MAIZE", "MAJOR", "MAKER", "MAKES", "MALES", "MALLS", "MALTS", "MALTY", "MAMAS", "MAMBA", "MAMBO", "MAMMY", "MANED", "MANES", "MANGE", 
"MANGO", "MANGY", "MANIA", "MANIC", "MANLY", "MANNA", "MANOR", "MANSE", "MANTA", "MAPLE", "MARCH", "MARES", "MARIA", "MARKS", "MARLS", "MARRY", "MARSH", "MARTS", "MASER", "MASES", 
"MASKS", "MASON", "MASTS", "MATCH", "MATED", "MATER", "MATES", "MATHS", "MATTE", "MATZO", "MAULS", "MAUVE", "MAVEN", "MAWED", "MAXED", "MAXES", "MAXIM", "MAXIS", "MAYBE", "MAYER", 
"MAYOR", "MAYOS", "MAYST", "MAZED", "MAZER", "MAZES", "MEADS", "MEALS", "MEALY", "MEANS", "MEANT", "MEATS", "MEATY", "MECCA", "MEDAL", "MEDIA", "MEDIC", "MEEDS", "MEETS", "MELDS", 
"MELEE", "MELON", "MELTS", "MEMES", "MEMOS", "MENDS", "MENUS", "MEOWS", "MERCY", "MERED", "MERER", "MERES", "MERGE", "MERIT", "MERRY", "MESAS", "MESES", "MESON", "MESSY", "METAL", 
"METED", "METER", "METES", "METRE", "METRO", "MEWED", "MEWLS", "MEZZO", "MIAOW", "MICAS", "MICRO", "MIDAS", "MIDDY", "MIDGE", "MIDIS", "MIDST", "MIENS", "MIFFS", "MIGHT", "MIKED", 
"MIKES", "MILCH", "MILDS", "MILER", "MILES", "MILKS", "MILKY", "MILLS", "MILTS", "MIMED", "MIMER", "MIMES", "MIMIC", "MINCE", "MINDS", "MINED", "MINER", "MINES", "MINIM", "MINIS", 
"MINKE", "MINKS", "MINOR", "MINTS", "MINTY", "MINUS", "MIRED", "MIRES", "MIRTH", "MISDO", "MISER", "MISES", "MISTS", "MISTY", "MITER", "MITES", "MITRE", "MITTS", "MIXED", "MIXER", 
"MIXES", "MOANS", "MOATS", "MOCHA", "MOCKS", "MODAL", "MODEL", "MODEM", "MODER", "MODES", "MODUS", "MOGUL", "MOILS", "MOIRE", "MOIST", "MOLAL", "MOLAR", "MOLDS", "MOLDY", "MOLES", 
"MOLLS", "MOLTS", "MOLLY", "MOMMA", "MOMMY", "MONAD", "MONEY", "MONKS", "MONOS", "MONTH", "MOOCH", "MOODS", "MOODY", "MOOED", "MOONS", "MOORS", "MOOSE", "MOOTS", "MOPED", "MOPER", 
"MOPES", "MOPEY", "MORAL", "MORAY", "MORED", "MOREL", "MORES", "MORNS", "MORON", "MORPH", "MOSES", "MOSEY", "MOSSY", "MOSTS", "MOTEL", "MOTES", "MOTET", "MOTHS", "MOTIF", "MOTOR", 
"MOTTO", "MOUED", "MOUES", "MOULD", "MOULT", "MOUND", "MOUNT", "MOURN", "MOUSE", "MOUSY", "MOUTH", "MOVED", "MOVER", "MOVES", "MOVIE", "MOWED", "MOWER", "MOXIE", "MUCKS", "MUCKY", 
"MUCUS", "MUDDY", "MUFFS", "MUFTI", "MUGGY", "MULCH", "MULCT", "MULED", "MULES", "MULLS", "MULTI", "MUMMY", "MUMPS", "MUNCH", "MUNGE", "MUNGS", "MURAL", "MURKS", "MURKY", "MUSED", 
"MUSER", "MUSES", "MUSHY", "MUSIC", "MUSKS", "MUSKY", "MUSSY", "MUSTS", "MUSTY", "MUTED", "MUTER", "MUTES", "MUTTS", "MUZAK", "MYERS", "MYLAR", "MYNAS", "MYRRH", "MYTHS", "NABOB", 
"NACHO", "NACRE", "NADIR", "NAIAD", "NAIFS", "NAILS", "NAIVE", "NAKED", "NAMED", "NAMER", "NAMES", "NANNY", "NAPES", "NAPPY", "NARCS", "NASAL", "NASTY", "NATAL", "NATCH", "NATTY", 
"NAVAL", "NAVEL", "NAVES", "NAVVY", "NEAPS", "NEARS", "NEATH", "NEATS", "NECKS", "NEEDS", "NEEDY", "NEIGH", "NEONS", "NERDS", "NERDY", "NERVE", "NERVY", "NESTS", "NETTS", "NEVER", 
"NEVUS", "NEWED", "NEWEL", "NEWER", "NEWLY", "NEWSY", "NEWTS", "NEXUS", "NICER", "NICHE", "NICKS", "NIECE", "NIFTY", "NIGHS", "NIGHT", "NILLY", "NIMBI", "NINES", "NINJA", "NINTH", 
"NINNY", "NIPPY", "NISEI", "NITER", "NITRE", "NIXED", "NIXER", "NIXES", "NOBLE", "NOBLY", "NODAL", "NODDY", "NODES", "NOELS", "NOHOW", "NOISE", "NOISY", "NOMAD", "NONCE", "NONES", 
"NOOKS", "NOONS", "NOOSE", "NOPES", "NORMS", "NORTH", "NOSED", "NOSES", "NOSEY", "NOTCH", "NOTED", "NOTER", "NOTES", "NOTRE", "NOUNS", "NOVAE", "NOVAS", "NOVEL", "NOWAY", "NROFF", 
"NUBBY", "NUDER", "NUDES", "NUDGE", "NUKED", "NUKES", "NULLS", "NUMBS", "NURSE", "NUTTY", "NYLON", "NYMPH", "OAKEN", "OAKUM", "OARED", "OASES", "OASIS", "OATEN", "OATER", "OATHS", 
"OBESE", "OBEYS", "OBIED", "OBITS", "OBOES", "OCCUR", "OCEAN", "OCHER", "OCHRE", "OCTAL", "OCTET", "ODDER", "ODDLY", "ODIUM", "ODORS", "ODOUR", "OFFAL", "OFFED", "OFFER", "OFTEN", 
"OFTER", "OGIVE", "OGLED", "OGLER", "OGLES", "OGRES", "OHMIC", "OILED", "OILER", "OINKS", "OKAPI", "OKRAS", "OLDEN", "OLDER", "OLDIE", "OLEOS", "OLIVE", "OMEGA", "OMENS", "OMITS", 
"ONCER", "ONCES", "ONION", "ONSET", "OOHED", "OOZED", "OOZES", "OPALS", "OPENS", "OPERA", "OPINE", "OPING", "OPIUM", "OPTED", "OPTIC", "ORALS", "ORATE", "ORBED", "ORBIT", "ORDER", 
"ORGAN", "ORIEL", "ORION", "ORRIS", "ORZOS", "OSIER", "OTHER", "OTTER", "OUGHT", "OUNCE", "OUSTS", "OUTDO", "OUTED", "OUTER", "OUTGO", "OUTRE", "OUZOS", "OVALS", "OVARY", "OVATE", 
"OVENS", "OVERS", "OVERT", "OVOID", "OVULE", "OVUMS", "OWING", "OWLED", "OWLER", "OWLET", "OWNED", "OWNER", "OXBOW", "OXIDE", "OZONE", "PACED", "PACER", "PACES", "PACKS", "PACTS", 
"PADDY", "PADRE", "PAEAN", "PAGAN", "PAGED", "PAGER", "PAGES", "PAILS", "PAINS", "PAINT", "PAIRS", "PALED", "PALER", "PALES", "PALLS", "PALMS", "PALMY", "PALSY", "PALLY", "PANDA", 
"PANED", "PANEL", "PANES", "PANGS", "PANIC", "PANSY", "PANTS", "PAPAL", "PAPAS", "PAPAW", "PAPEN", "PAPER", "PAPPY", "PARAS", "PARCH", "PARED", "PARER", "PARES", "PARKA", "PARKS", 
"PARRY", "PARSE", "PARTS", "PARTY", "PASES", "PASHA", "PASSE", "PASTA", "PASTE", "PASTS", "PASTY", "PATCH", "PATED", "PATEN", "PATER", "PATES", "PATHS", "PATIO", "PATSY", "PATTY", 
"PAUSE", "PAVED", "PAVER", "PAVES", "PAWED", "PAWLS", "PAWNS", "PAXES", "PAYED", "PAYEE", "PAYER", "PCRES", "PEACE", "PEACH", "PEAKS", "PEAKY", "PEALS", "PEARL", "PEARS", "PEATS", 
"PEATY", "PECAN", "PECKS", "PEDAL", "PEEKS", "PEELS", "PEENS", "PEEPS", "PEEPY", "PEERS", "PEEVE", "PEKES", "PEKOE", "PELFS", "PELTS", "PENAL", "PENCE", "PENDS", "PENIS", "PENTS", 
"PENNY", "PEONS", "PEONY", "PEPPY", "PERCH", "PERIL", "PERKS", "PERKY", "PERMS", "PERTS", "PESKY", "PESOS", "PESTO", "PESTS", "PETAL", "PETER", "PETRI", "PETTY", "PEWEE", "PEWIT", 
"PHAGE", "PHASE", "PHEWS", "PHIAL", "PHLOX", "PHONE", "PHONY", "PHOTO", "PHYLA", "PIANO", "PICAS", "PICKS", "PICKY", "PICOT", "PIECE", "PIERS", "PIETY", "PIGGY", "PIING", "PIKED", 
"PIKER", "PIKES", "PILAF", "PILED", "PILES", "PILLS", "PILOT", "PIMPS", "PINCH", "PINED", "PINES", "PINGS", "PINKO", "PINKS", "PINON", "PINTO", "PINTS", "PINUP", "PIOUS", "PIPED", 
"PIPER", "PIPES", "PIPIT", "PIQUE", "PISTE", "PITAS", "PITCH", "PITHS", "PITHY", "PITON", "PIVOT", "PIXED", "PIXEL", "PIXES", "PIXIE", "PIZZA", "PLACE", "PLAID", "PLAIN", "PLAIT", 
"PLANE", "PLANK", "PLANS", "PLANT", "PLASH", "PLASM", "PLATE", "PLATS", "PLATY", "PLAYS", "PLAZA", "PLEAD", "PLEAS", "PLEAT", "PLEBE", "PLIED", "PLIER", "PLIES", "PLINK", "PLODS", 
"PLONK", "PLOPS", "PLOTS", "PLOWS", "PLOYS", "PLUCK", "PLUGS", "PLUMB", "PLUME", "PLUMP", "PLUMS", "PLUMY", "PLUNK", "PLUSH", "POACH", "POCKS", "PODGE", "POEMS", "POESY", "POETS", 
"POINT", "POISE", "POKED", "POKER", "POKES", "POLAR", "POLED", "POLER", "POLES", "POLIO", "POLIS", "POLKA", "POLLS", "POLOS", "POLYP", "POMPS", "PONCE", "PONDS", "PONES", "POOCH", 
"POOFS", "POOHS", "POOLS", "POOPS", "POPES", "POPPY", "PORCH", "PORED", "PORER", "PORES", "PORGY", "PORKS", "PORKY", "PORNO", "PORNS", "PORTS", "POSED", "POSER", "POSES", "POSIT", 
"POSSE", "POSTS", "POTTY", "POUCH", "POUND", "POURS", "POUTS", "POWER", "POXED", "POXES", "PRAMS", "PRANK", "PRATE", "PRAWN", "PRAYS", "PREEN", "PREPS", "PRESS", "PREYS", "PRICE", 
"PRICK", "PRIDE", "PRIED", "PRIER", "PRIES", "PRIGS", "PRIME", "PRIMP", "PRIMS", "PRINT", "PRIOR", "PRISE", "PRISM", "PRIVY", "PRIZE", "PROBE", "PRODS", "PROFS", "PROMO", "PROMS", 
"PRONE", "PRONG", "PROOF", "PROPS", "PROSE", "PROSY", "PROUD", "PROVE", "PROWL", "PROWS", "PROXY", "PRUDE", "PRUNE", "PSALM", "PSHAW", "PSSTS", "PSYCH", "PUBES", "PUBIC", "PUBIS", 
"PUCES", "PUCKS", "PUDGY", "PUERS", "PUFFS", "PUFFY", "PUKED", "PUKES", "PUKKA", "PULED", "PULES", "PULLS", "PULPS", "PULPY", "PULSE", "PUMAS", "PUMPS", "PUNCH", "PUNKS", "PUNKY", 
"PUNTS", "PUPAE", "PUPAL", "PUPIL", "PUPPY", "PURED", "PUREE", "PURER", "PURES", "PURGE", "PURLS", "PURRS", "PURSE", "PUSES", "PUSHY", "PUSSY", "PUTTS", "PUTTY", "PYGMY", "PYLON", 
"PYRES", "PYXED", "PYXES", "QUACK", "QUADS", "QUAFF", "QUAIL", "QUAKE", "QUAKY", "QUALM", "QUARK", "QUART", "QUASH", "QUASI", "QUAYS", "QUEEN", "QUEER", "QUELL", "QUERN", "QUERY", 
"QUEST", "QUEUE", "QUICK", "QUIDS", "QUIET", "QUILL", "QUILT", "QUINE", "QUINT", "QUIPS", "QUIRE", "QUIRK", "QUIRT", "QUITE", "QUITS", "QUOIN", "QUOIT", "QUOTA", "QUOTE", "QUOTH", 
"RABBI", "RABID", "RABIS", "RACED", "RACER", "RACES", "RACKS", "RADAR", "RADII", "RADIO", "RADIX", "RADON", "RAFTS", "RAGAS", "RAGED", "RAGES", "RAHED", "RAIDS", "RAILS", "RAINS", 
"RAINY", "RAISE", "RAJAH", "RAKED", "RAKER", "RAKES", "RALLY", "RAMIE", "RAMPS", "RANCH", "RANDS", "RANDY", "RANEE", "RANGE", "RANGY", "RANKS", "RANTS", "RAPED", "RAPER", "RAPES", 
"RAPID", "RARED", "RARER", "RARES", "RASPS", "RASPY", "RATED", "RATER", "RATES", "RATIO", "RATTY", "RAVED", "RAVEL", "RAVEN", "RAVER", "RAVES", "RAWER", "RAWLY", "RAYED", "RAYON", 
"RAZED", "RAZER", "RAZES", "RAZOR", "REACH", "REACT", "READS", "READY", "REALM", "REALS", "REAMS", "REAPS", "REARM", "REARS", "REBEL", "REBID", "REBUS", "REBUT", "RECAP", "RECTO", 
"RECUR", "REDID", "REDLY", "REDYE", "REEDS", "REEDY", "REEFS", "REEKS", "REELS", "REEVE", "REFER", "REFIT", "REFRY", "REGAL", "REHAB", "REIGN", "REINS", "RELAX", "RELAY", "RELIC", 
"REMAP", "REMIT", "REMIX", "RENAL", "RENDS", "RENEW", "RENTS", "REPAY", "REPEL", "REPLY", "RERAN", "RERUN", "RESET", "RESEW", "RESIN", "RESIT", "RESOW", "RESTS", "RETCH", "RETIE", 
"RETRO", "RETRY", "REUSE", "REVEL", "REVET", "REVUE", "REWED", "REXES", "RHEAS", "RHEUM", "RHINO", "RHYME", "RIALS", "RICED", "RICER", "RICES", "RICKS", "RIDER", "RIDES", "RIDGE", 
"RIDGY", "RIFER", "RIFFS", "RIFLE", "RIFTS", "RIGHT", "RIGID", "RIGOR", "RILED", "RILES", "RILLS", "RIMED", "RIMER", "RIMES", "RINDS", "RINGS", "RINKS", "RINSE", "RIOTS", "RIPED", 
"RIPEN", "RIPER", "RIPES", "RISEN", "RISER", "RISES", "RISKS", "RISKY", "RITED", "RITES", "RITZY", "RIVAL", "RIVED", "RIVEN", "RIVER", "RIVES", "RIVET", "RIYAL", "ROACH", "ROADS", 
"ROAMS", "ROANS", "ROARS", "ROAST", "ROBED", "ROBES", "ROBIN", "ROBOT", "ROCKS", "ROCKY", "RODED", "RODEO", "RODES", "ROGER", "ROGUE", "ROILS", "ROLES", "ROLLS", "ROMAN", "ROMEO", 
"ROMPS", "RONDO", "ROODS", "ROOFS", "ROOKS", "ROOMS", "ROOMY", "ROOST", "ROOTS", "ROPED", "ROPER", "ROPES", "ROSED", "ROSES", "ROSIN", "ROTAS", "ROTED", "ROTES", "ROTOR", "ROUÉS", 
"ROUGE", "ROUGH", "ROUND", "ROUSE", "ROUST", "ROUTE", "ROUTS", "ROVED", "ROVER", "ROVES", "ROWDY", "ROWED", "ROWEL", "ROWEN", "ROWER", "ROYAL", "RUBES", "RUBLE", "RUDDY", "RUDER", 
"RUFFS", "RUGBY", "RUING", "RUINS", "RULED", "RULER", "RULES", "RUMBA", "RUMEN", "RUMMY", "RUMOR", "RUMPS", "RUNES", "RUNGS", "RUNIC", "RUNTS", "RUNTY", "RUNNY", "RUPEE", "RURAL", 
"RUSES", "RUSHY", "RUSKS", "RUSTS", "RUSTY", "RUTTY", "SABER", "SABLE", "SABOT", "SABRA", "SABRE", "SACKS", "SACRA", "SADES", "SADLY", "SAFER", "SAFES", "SAGAS", "SAGER", "SAGES", 
"SAGOS", "SAGGY", "SAHIB", "SAIDS", "SAILS", "SAINT", "SAITH", "SAKER", "SAKES", "SALAD", "SALES", "SALON", "SALSA", "SALTS", "SALTY", "SALVE", "SALVO", "SALLY", "SAMBA", "SAMES", 
"SANDS", "SANDY", "SANED", "SANER", "SANES", "SANGS", "SAPPY", "SARAN", "SARGE", "SARIS", "SASSY", "SATED", "SATES", "SATIN", "SATYR", "SAUCE", "SAUCY", "SAUNA", "SAUTÉ", "SAVED", 
"SAVER", "SAVES", "SAVOR", "SAVOY", "SAVVY", "SAWED", "SAWER", "SAXES", "SAYER", "SCABS", "SCADS", "SCAGS", "SCALD", "SCALE", "SCALP", "SCALY", "SCAMP", "SCAMS", "SCANS", "SCANT", 
"SCAPE", "SCARE", "SCARF", "SCARP", "SCARS", "SCARY", "SCATS", "SCENE", "SCENT", "SCHMO", "SCHWA", "SCION", "SCOFF", "SCOLD", "SCONE", "SCOOP", "SCOOT", "SCOPE", "SCOPS", "SCORE", 
"SCORN", "SCOUR", "SCOUT", "SCOWL", "SCOWS", "SCRAG", "SCRAM", "SCRAP", "SCREE", "SCREW", "SCRIM", "SCRIP", "SCROD", "SCROG", "SCRUB", "SCRUM", "SCUBA", "SCUDS", "SCUFF", "SCULL", 
"SCUMS", "SCURF", "SEALS", "SEALY", "SEAMS", "SEAMY", "SEARS", "SEATS", "SECTS", "SEDAN", "SEDGE", "SEDGY", "SEEDS", "SEEDY", "SEEKS", "SEEMS", "SEEPS", "SEERS", "SEGUE", "SEINE", 
"SEIZE", "SELFS", "SELLS", "SEMEN", "SEMIS", "SENDS", "SENNA", "SENOR", "SENSE", "SEPAL", "SEPIA", "SEPTA", "SERED", "SERER", "SERES", "SERFS", "SERGE", "SERIF", "SERUM", "SERVE", 
"SERVO", "SETTS", "SETUP", "SEVEN", "SEVER", "SEWED", "SEWER", "SEXED", "SEXES", "SHACK", "SHADE", "SHADS", "SHADY", "SHAFT", "SHAGS", "SHAHS", "SHAKE", "SHAKY", "SHALE", "SHALL", 
"SHALT", "SHAME", "SHAMS", "SHANK", "SHAPE", "SHARD", "SHARE", "SHARK", "SHARP", "SHAVE", "SHAWL", "SHAYS", "SHEAF", "SHEAR", "SHEDS", "SHEEN", "SHEEP", "SHEER", "SHEET", "SHEIK", 
"SHELF", "SHELL", "SHEWN", "SHEWS", "SHIED", "SHIER", "SHIES", "SHIFT", "SHILL", "SHIMS", "SHINE", "SHINS", "SHINY", "SHIPS", "SHIRE", "SHIRK", "SHIRR", "SHIRT", "SHITS", "SHIVS", 
"SHOAL", "SHOAT", "SHOCK", "SHOER", "SHOES", "SHONE", "SHOOK", "SHOOS", "SHOOT", "SHOPS", "SHORE", "SHORT", "SHOTS", "SHOUT", "SHOVE", "SHOWN", "SHOWS", "SHOWY", "SHRED", "SHREW", 
"SHRUB", "SHRUG", "SHUCK", "SHUNS", "SHUNT", "SHUSH", "SHUTS", "SHYER", "SHYLY", "SIBYL", "SICKO", "SICKS", "SIDED", "SIDER", "SIDES", "SIDLE", "SIEGE", "SIEVE", "SIFTS", "SIGHS", 
"SIGHT", "SIGMA", "SIGNS", "SILED", "SILKS", "SILKY", "SILLS", "SILOS", "SILTS", "SILTY", "SILLY", "SINCE", "SINES", "SINEW", "SINGE", "SINGS", "SINKS", "SINUS", "SIRED", "SIREN", 
"SIRES", "SISAL", "SISES", "SISSY", "SITAR", "SITED", "SITES", "SITUS", "SIXER", "SIXES", "SIXTH", "SIXTY", "SIZED", "SIZER", "SIZES", "SKATE", "SKEET", "SKEIN", "SKEWS", "SKIDS", 
"SKIED", "SKIEN", "SKIER", "SKIES", "SKIFF", "SKILL", "SKIMP", "SKIMS", "SKINS", "SKIPS", "SKIRT", "SKITS", "SKOAL", "SKULK", "SKULL", "SKUNK", "SLABS", "SLACK", "SLAGS", "SLAIN", 
"SLAKE", "SLAMS", "SLANG", "SLANT", "SLAPS", "SLASH", "SLATE", "SLATS", "SLAVE", "SLAWS", "SLAYS", "SLEDS", "SLEEK", "SLEEP", "SLEET", "SLEPT", "SLEWS", "SLICE", "SLICK", "SLIDE", 
"SLIER", "SLIME", "SLIMS", "SLIMY", "SLING", "SLINK", "SLIPS", "SLITS", "SLOBS", "SLOES", "SLOGS", "SLOOP", "SLOPE", "SLOPS", "SLOSH", "SLOTH", "SLOTS", "SLOWS", "SLUED", "SLUES", 
"SLUGS", "SLUMP", "SLUMS", "SLUNG", "SLUNK", "SLURP", "SLURS", "SLUSH", "SLUTS", "SLYLY", "SMACK", "SMALL", "SMART", "SMASH", "SMEAR", "SMELL", "SMELT", "SMILE", "SMIRK", "SMITE", 
"SMITH", "SMOCK", "SMOGS", "SMOKE", "SMOKY", "SMOTE", "SMUGS", "SMURF", "SMUTS", "SNACK", "SNAFU", "SNAGS", "SNAIL", "SNAKE", "SNAKY", "SNAPS", "SNARE", "SNARF", "SNARK", "SNARL", 
"SNEAK", "SNEER", "SNICK", "SNIDE", "SNIFF", "SNIPE", "SNIPS", "SNITS", "SNOBS", "SNOOD", "SNOOK", "SNOOP", "SNOOT", "SNORE", "SNORT", "SNOTS", "SNOUT", "SNOWS", "SNOWY", "SNUBS", 
"SNUFF", "SNUGS", "SOAKS", "SOAPS", "SOAPY", "SOARS", "SOBER", "SOCIO", "SOCKS", "SODAS", "SOFAS", "SOFTS", "SOFTY", "SOGGY", "SOILS", "SOLAR", "SOLED", "SOLER", "SOLES", "SOLID", 
"SOLOS", "SOLVE", "SONAR", "SONGS", "SONIC", "SONLY", "SONNY", "SOOTH", "SOOTS", "SOOTY", "SOPPY", "SORED", "SORER", "SORES", "SORRY", "SORTA", "SORTS", "SOUGH", "SOULS", "SOUND", 
"SOUPS", "SOUPY", "SOURS", "SOUSE", "SOUTH", "SOWED", "SOWER", "SPACE", "SPADE", "SPAKE", "SPAMS", "SPANK", "SPANS", "SPARE", "SPARK", "SPARS", "SPASM", "SPATE", "SPATS", "SPAWN", 
"SPAYS", "SPEAK", "SPEAR", "SPECK", "SPECS", "SPEED", "SPEER", "SPELL", "SPELT", "SPEND", "SPENT", "SPERE", "SPERM", "SPEWS", "SPICE", "SPICY", "SPIED", "SPIEL", "SPIER", "SPIES", 
"SPIKE", "SPIKY", "SPILL", "SPILT", "SPINE", "SPINS", "SPINY", "SPIRE", "SPIRY", "SPITE", "SPITS", "SPLAT", "SPLAY", "SPLIT", "SPOIL", "SPOKE", "SPOOF", "SPOOK", "SPOOL", "SPOON", 
"SPOOR", "SPORE", "SPORT", "SPOTS", "SPOUT", "SPRAT", "SPRAY", "SPREE", "SPRIG", "SPRUE", "SPUDS", "SPUME", "SPUMY", "SPUNK", "SPURN", "SPURS", "SPURT", "SPUTA", "SQUAB", "SQUAD", 
"SQUAT", "SQUAW", "SQUIB", "SQUID", "STABS", "STACK", "STAFF", "STAGE", "STAGS", "STAGY", "STAID", "STAIN", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND", "STANK", 
"STAPH", "STARE", "STARK", "STARS", "START", "STASH", "STATE", "STATS", "STAVE", "STAYS", "STDIO", "STEAD", "STEAK", "STEAL", "STEAM", "STEED", "STEEL", "STEEP", "STEER", "STEIN", 
"STEMS", "STENO", "STEPS", "STERN", "STETS", "STEWS", "STICK", "STIED", "STIES", "STIFF", "STILE", "STILL", "STILT", "STING", "STINK", "STINT", "STIRS", "STOAT", "STOCK", "STOGY", 
"STOIC", "STOKE", "STOLE", "STOMP", "STONE", "STONY", "STOOD", "STOOL", "STOOP", "STOPS", "STORE", "STORK", "STORM", "STORY", "STOUP", "STOUT", "STOVE", "STOWS", "STRAP", "STRAW", 
"STRAY", "STREP", "STREW", "STRIA", "STRIP", "STROP", "STRUM", "STRUT", "STUBS", "STUCK", "STUDS", "STUDY", "STUFF", "STUMP", "STUNG", "STUNK", "STUNS", "STUNT", "STYLE", "STYLI", 
"SUAVE", "SUCKS", "SUDSY", "SUEDE", "SUERS", "SUETS", "SUETY", "SUGAR", "SUING", "SUITE", "SUITS", "SULFA", "SULKS", "SULKY", "SULLY", "SUMAC", "SUMER", "SUMOS", "SUMPS", "SUNKS", 
"SUNUP", "SUNNY", "SUPER", "SUPPL", "SUPRA", "SURED", "SURER", "SURES", "SURFS", "SURGE", "SURLY", "SUSHI", "SWABS", "SWAGS", "SWAIN", "SWAMI", "SWAMP", "SWANK", "SWANS", "SWAPS", 
"SWARD", "SWARM", "SWART", "SWASH", "SWATH", "SWATS", "SWAYS", "SWEAR", "SWEAT", "SWEDE", "SWEEP", "SWEET", "SWELL", "SWEPT", "SWIFT", "SWIGS", "SWILL", "SWIMS", "SWINE", "SWING", 
"SWIPE", "SWIRL", "SWISH", "SWISS", "SWOON", "SWOOP", "SWORD", "SWORE", "SWORN", "SWOTS", "SWUNG", "SYLPH", "SYNCS", "SYNOD", "SYRUP", "SYSOP", "TABBY", "TABLA", "TABLE", "TABOO", 
"TABOR", "TACIT", "TACKS", "TACKY", "TACOS", "TACTS", "TAELS", "TAFFY", "TAIGA", "TAILS", "TAINT", "TAKEN", "TAKER", "TAKES", "TALCS", "TALER", "TALES", "TALKS", "TALKY", "TALON", 
"TALUS", "TALLY", "TAMED", "TAMER", "TAMES", "TAMPS", "TANGO", "TANGS", "TANGY", "TANKS", "TANSY", "TAPED", "TAPER", "TAPES", "TAPIR", "TARDY", "TARED", "TARES", "TARNS", "TAROS", 
"TAROT", "TARPS", "TARRY", "TARSI", "TARTS", "TASKS", "TASTE", "TASTY", "TATER", "TATTY", "TAUNT", "TAUPE", "TAUTS", "TAWNY", "TAXED", "TAXER", "TAXES", "TAXIS", "TEACH", "TEAED", 
"TEAER", "TEAKS", "TEALS", "TEAMS", "TEARS", "TEARY", "TEASE", "TEATS", "TECHS", "TEDDY", "TEEMS", "TEENS", "TEENY", "TEETH", "TELEX", "TELLS", "TELLY", "TEMPO", "TEMPS", "TEMPT", 
"TENCH", "TENDS", "TENET", "TENON", "TENOR", "TENSE", "TENTH", "TENTS", "TEPEE", "TEPID", "TERMS", "TERNS", "TERRS", "TERRY", "TERSE", "TESTS", "TESTY", "TETRA", "TEXTS", "THANE", 
"THANK", "THATS", "THAWS", "THEED", "THEES", "THEFT", "THEIR", "THEME", "THENS", "THERE", "THERM", "THESE", "THETA", "THEWS", "THICK", "THIEF", "THIGH", "THINE", "THING", "THINK", 
"THINS", "THIRD", "THOLE", "THONG", "THORN", "THOSE", "THOUS", "THREE", "THREW", "THROB", "THROE", "THROW", "THRUM", "THUDS", "THUGS", "THUMB", "THUMP", "THUNK", "THYME", "TIARA", 
"TIBIA", "TICKS", "TIDAL", "TIDED", "TIDES", "TIERS", "TIFFS", "TIGER", "TIGHT", "TILDE", "TILED", "TILER", "TILES", "TILLS", "TILTH", "TILTS", "TIMED", "TIMER", "TIMES", "TIMID", 
"TINED", "TINES", "TINGE", "TINGS", "TINTS", "TINNY", "TIPPY", "TIPSY", "TIRED", "TIRES", "TITAN", "TITER", "TITHE", "TITLE", "TITRE", "TIZZY", "TOADS", "TOADY", "TOAST", "TODAY", 
"TODDY", "TOFUS", "TOGAE", "TOGAS", "TOILS", "TOKED", "TOKEN", "TOKES", "TOLED", "TOLES", "TOLLS", "TOMBS", "TOMES", "TOMMY", "TONAL", "TONED", "TONER", "TONES", "TONGS", "TONIC", 
"TONKS", "TONNE", "TOOLS", "TOOTH", "TOOTS", "TOPAZ", "TOPED", "TOPER", "TOPIC", "TOQUE", "TORCH", "TORES", "TORSO", "TORTE", "TORTS", "TORUS", "TOTAL", "TOTED", "TOTEM", "TOTER", 
"TOTES", "TOUCH", "TOUGH", "TOURS", "TOUTS", "TOWED", "TOWEL", "TOWER", "TOWNS", "TOXIC", "TOXIN", "TOYED", "TOYER", "TRACE", "TRACK", "TRACT", "TRADE", "TRAIL", "TRAIN", "TRAIT", 
"TRAMP", "TRAMS", "TRANS", "TRAPS", "TRASH", "TRAWL", "TRAYS", "TREAD", "TREAS", "TREAT", "TREED", "TREES", "TREKS", "TREND", "TRESS", "TREYS", "TRIAD", "TRIAL", "TRIBE", "TRICE", 
"TRICK", "TRIED", "TRIER", "TRIES", "TRIGS", "TRIKE", "TRILL", "TRIMS", "TRIOS", "TRIPE", "TRIPS", "TRITE", "TROFF", "TROLL", "TROMP", "TRONS", "TROOP", "TROPE", "TROTH", "TROTS", 
"TROUT", "TROVE", "TROWS", "TROYS", "TRUCE", "TRUCK", "TRUED", "TRUER", "TRUES", "TRULY", "TRUMP", "TRUNK", "TRUSS", "TRUST", "TRUTH", "TRYST", "TSARS", "TUBAE", "TUBAL", "TUBAS", 
"TUBBY", "TUBED", "TUBER", "TUBES", "TUCKS", "TUFTS", "TULIP", "TULLE", "TUMID", "TUMMY", "TUMOR", "TUNAS", "TUNED", "TUNER", "TUNES", "TUNIC", "TUNNY", "TUPLE", "TUQUE", "TURBO", 
"TURDS", "TURFS", "TURFY", "TURKS", "TURNS", "TURVY", "TUSKS", "TUTOR", "TUTTI", "TUTUS", "TUXES", "TWAIN", "TWANG", "TWEAK", "TWEED", "TWEEN", "TWEET", "TWERP", "TWICE", "TWIGS", 
"TWILL", "TWINE", "TWINK", "TWINS", "TWIRL", "TWIST", "TWITS", "TWIXT", "TYING", "TYKES", "TYNED", "TYNES", "TYPED", "TYPER", "TYPES", "TYPOS", "TYRED", "TYREO", "TYRES", "TYROS", 
"UDDER", "UGLIS", "UKASE", "ULCER", "ULNAE", "ULNAR", "ULTRA", "UMBEL", "UMBER", "UMBRA", "UMIAK", "UMPED", "UNAPT", "UNARY", "UNBAR", "UNBID", "UNCAP", "UNCLE", "UNCUT", "UNDER", 
"UNDID", "UNDUE", "UNFED", "UNFIT", "UNFIX", "UNGOT", "UNIFY", "UNION", "UNITE", "UNITS", "UNITY", "UNJAM", "UNLIT", "UNMAN", "UNMET", "UNPIN", "UNSAY", "UNSEE", "UNSET", "UNTIE", 
"UNTIL", "UNWED", "UNZIP", "UPEND", "UPPED", "UPPER", "UPSET", "URBAN", "UREAS", "URGED", "URGER", "URGES", "URINE", "URNED", "USAGE", "USERS", "USHER", "USING", "USUAL", "USURP", 
"USURY", "UTERI", "UTILE", "UTTER", "UVULA", "VACUO", "VAGUE", "VALES", "VALET", "VALID", "VALOR", "VALUE", "VALVE", "VAMPS", "VANED", "VANES", "VAPID", "VAPOR", "VASES", "VASTS", 
"VAULT", "VAUNT", "VEALS", "VEEPS", "VEERS", "VEGAN", "VEGES", "VEILS", "VEINS", "VELAR", "VELDS", "VELOR", "VELUM", "VENAL", "VENDS", "VENOM", "VENTS", "VENUE", "VERBS", "VERGE", 
"VERSA", "VERSE", "VERSO", "VERVE", "VESTS", "VETCH", "VETER", "VEXED", "VEXES", "VIALS", "VIAND", "VIBES", "VICAR", "VICED", "VICES", "VIDEO", "VIEWS", "VIGIL", "VIGOR", "VILER", 
"VILLA", "VILLE", "VILLI", "VINED", "VINES", "VINOS", "VINYL", "VIOLA", "VIOLS", "VIPER", "VIRAL", "VIREO", "VIRUS", "VISAS", "VISED", "VISES", "VISIT", "VISOR", "VISTA", "VITAE", 
"VITAL", "VITRO", "VIVAS", "VIVID", "VIXEN", "VOCAB", "VOCAL", "VODKA", "VOGUE", "VOICE", "VOIDS", "VOILE", "VOILR", "VOLAR", "VOLED", "VOLES", "VOLTS", "VOMIT", "VOTED", "VOTER", 
"VOTES", "VOUCH", "VOWED", "VOWEL", "VOWER", "VULVA", "VYING", "WACKO", "WACKY", "WADED", "WADER", "WADES", "WADIS", "WAFER", "WAFTS", "WAGED", "WAGER", "WAGES", "WAGON", "WAIFS", 
"WAILS", "WAINS", "WAIST", "WAITS", "WAIVE", "WAKED", "WAKEN", "WAKER", "WAKES", "WALDO", "WALED", "WALER", "WALES", "WALKS", "WALLS", "WALTZ", "WALLY", "WANDS", "WANED", "WANES", 
"WANKS", "WANLY", "WANNA", "WANTS", "WARDS", "WARED", "WARES", "WAREZ", "WARMS", "WARNS", "WARPS", "WARTS", "WARTY", "WASES", "WASHY", "WASPS", "WASTE", "WASTS", "WATCH", "WATER", 
"WATTS", "WAVED", "WAVER", "WAVES", "WAXED", "WAXEN", "WAXER", "WAXES", "WEALS", "WEANS", "WEARS", "WEARY", "WEAVE", "WEBER", "WEDGE", "WEEDS", "WEEDY", "WEEKS", "WEENS", "WEENY", 
"WEEPS", "WEEPY", "WEEST", "WEFTS", "WEIGH", "WEIRD", "WEIRS", "WELDS", "WELLS", "WELSH", "WELTS", "WENCH", "WENDS", "WESTS", "WETLY", "WHACK", "WHALE", "WHAMS", "WHARF", "WHATS", 
"WHEAL", "WHEAT", "WHEEL", "WHEES", "WHELK", "WHELM", "WHELP", "WHENS", "WHERE", "WHETS", "WHEWS", "WHEYS", "WHICH", "WHIFF", "WHIGS", "WHILE", "WHIMS", "WHINE", "WHINY", "WHIPS", 
"WHIRL", "WHIRS", "WHISK", "WHIST", "WHITE", "WHITS", "WHIZZ", "WHOAS", "WHOLE", "WHOOP", "WHORE", "WHORL", "WHOSE", "WHOSO", "WICKS", "WIDEN", "WIDER", "WIDES", "WIDOW", "WIDTH", 
"WIELD", "WIFED", "WIFES", "WIGHT", "WILDS", "WILED", "WILES", "WILLS", "WILTS", "WIMPS", "WIMPY", "WINCE", "WINCH", "WINDS", "WINDY", "WINED", "WINER", "WINES", "WINGS", "WINKS", 
"WINOS", "WIPED", "WIPER", "WIPES", "WIRED", "WIRER", "WIRES", "WISED", "WISEN", "WISER", "WISES", "WISHY", "WISPS", "WISPY", "WISTS", "WITCH", "WITHE", "WITHS", "WITTY", "WIVED", 
"WIVES", "WIZEN", "WOADS", "WOKEN", "WOLDS", "WOLFS", "WOMAN", "WOMBS", "WOMEN", "WONKS", "WONKY", "WONTS", "WOODS", "WOODY", "WOOED", "WOOER", "WOOFS", "WOOLS", "WOOZY", "WORDS", 
"WORDY", "WORKS", "WORLD", "WORMS", "WORMY", "WORRY", "WORSE", "WORST", "WORTH", "WORTS", "WOULD", "WOUND", "WOVEN", "WOWED", "WRACK", "WRAPS", "WRATH", "WREAK", "WRECK", "WRENS", 
"WREST", "WRIED", "WRIES", "WRING", "WRIST", "WRITE", "WRITS", "WRONG", "WROTE", "WROTH", "WRUNG", "WRYER", "WRYLY", "WURST", "WUSSY", "XCVII", "XENON", "XEROX", "XREFS", "XTERM", 
"XVIII", "XXIII", "XXVII", "XXXII", "XXXIV", "XXXIX", "XXXVI", "XYLEM", "YACHT", "YAHOO", "YANGS", "YANKS", "YARDS", "YARNS", "YAWED", "YAWLS", "YAWNS", "YEAHS", "YEARN", "YEARS", 
"YEAST", "YECCH", "YEGGS", "YELLS", "YELPS", "YESES", "YETIS", "YIELD", "YIKES", "YIPES", "YODEL", "YOGAS", "YOGIS", "YOKED", "YOKEL", "YOKES", "YOLKS", "YORES", "YOUNG", "YOURS", 
"YOUTH", "YOWED", "YOWLS", "YUCCA", "YUCKS", "YUCKY", "YULES", "YUMMY", "YURTS", "ZEALS", "ZEBRA", "ZEBUS", "ZEROS", "ZESTS", "ZESTY", "ZETAS", "ZILCH", "ZINCS", "ZINGS", "ZINGY", 
"ZIPPY", "ZLOTY", "ZONAL", "ZONED", "ZONER", "ZONES", "ZOOMS", "ZORCH"
    ];
    this.inputLockedUntil = 0;
    this.gameVersion = 0;
    this.ROWS = 6;
    this.COLS = 5;
    this.boardEl = boardEl;
    this.keyboardEl = keyboardEl;
    this.msgEl = msgEl;

    this.solution = "";
    this.grid = [];
    this.curRow = 0;
    this.curCol = 0;
    this.gameOver = false;
    this.keyState = {};

    this.handleKeyDown = (e) => this.onKeyDown(e);
    window.addEventListener("keydown", this.handleKeyDown);
  }

  init() {
    this.gameVersion++;
    this.boardEl.innerHTML = "";
    this.keyboardEl.innerHTML = "";
    this.msgEl.textContent = "";
    this.msgEl.className = "";

    this.solution = this.WORDS[Math.floor(Math.random() * this.WORDS.length)].toUpperCase();
    this.grid = Array.from({ length: this.ROWS }, () => Array(this.COLS).fill(""));
    this.curRow = 0;
    this.curCol = 0;
    this.gameOver = false;
    this.keyState = {};

    for (let r = 0; r < this.ROWS; r++) {
      const row = document.createElement("div");
      row.className = "row";
      for (let c = 0; c < this.COLS; c++) {
        const t = document.createElement("div");
        t.className = "tile";
        t.dataset.r = r;
        t.dataset.c = c;
        row.appendChild(t);
      }
      this.boardEl.appendChild(row);
    }

    const rows = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"];
    rows.forEach((keys, idx) => {
      const row = document.createElement("div");
      row.className = "keys";
      if (idx === 2) row.appendChild(this.mkKey("Enter", "Enter", "wide"));
      for (const ch of keys) row.appendChild(this.mkKey(ch));
      if (idx === 2) row.appendChild(this.mkKey("Back", "Back", "wide"));
      this.keyboardEl.appendChild(row);
    });
  }

  mkKey(label, action = label, extraClass = "") {
    const k = document.createElement("div");
    k.className = "key " + extraClass;
    k.textContent = label;
    k.dataset.key = action;
    k.addEventListener("click", () => this.handleInput(action));
    return k;
  }

  onKeyDown(e) {
    if (this.gameOver) return;
    let k = e.key;
    if (k === "Enter") this.handleInput("Enter");
    else if (k === "Backspace") this.handleInput("Back");
    else {
      k = k.toUpperCase();
      if (/^[A-Z]$/.test(k)) this.handleInput(k);
    }
  }

  handleInput(key) {
  if (this.gameOver || Date.now() < this.inputLockedUntil) return;

  if (key === "Enter") return this.submitRow();
  if (key === "Back") return this.backspace();

  if (key.length === 1 && this.curCol < this.COLS) {
    this.grid[this.curRow][this.curCol] = key;
    this.updateTile(this.curRow, this.curCol, key);
    this.curCol++;
  }
}

  updateTile(r, c, val) {
    const tile = this.boardEl.querySelector(`.tile[data-r="${r}"][data-c="${c}"]`);
    tile.textContent = val;
    tile.classList.toggle("filled", !!val);
  }

  backspace() {
    if (this.curCol > 0) {
      this.curCol--;
      this.grid[this.curRow][this.curCol] = "";
      this.updateTile(this.curRow, this.curCol, "");
    }
  }

  submitRow() {
    if (this.curCol < this.COLS) return this.showMessage("Chưa đủ 5 chữ!", 2000);
    const guess = this.grid[this.curRow].join("");
    
    if (!this.WORDS.includes(guess)) {
      this.showMessage("Từ không hợp lệ", 1500);
      for (let i = 0; i < this.COLS; i++) {
        this.grid[this.curRow][i] = "";
        this.updateTile(this.curRow, i, "");
      }
      this.curCol = 0;
      return;
    }
    this.inputLockedUntil = Date.now() + 1200;
    const solArr = this.solution.split("");
    const guessArr = guess.split("");
    const result = Array(this.COLS).fill("absent");

    for (let i = 0; i < this.COLS; i++) {
      if (guessArr[i] === solArr[i]) {
        result[i] = "correct";
        solArr[i] = null;
      }
    }

    for (let i = 0; i < this.COLS; i++) {
      if (result[i] === "correct") continue;
      const idx = solArr.indexOf(guessArr[i]);
      if (idx !== -1) {
        result[i] = "present";
        solArr[idx] = null;
      }
    }

    this.revealRow(this.curRow, guessArr, result).then(() => {
      for (let i = 0; i < this.COLS; i++) {
        const ch = guessArr[i];
        const prev = this.keyState[ch];
        const state = result[i];
        if (!prev || prev === "absent" && state !== "absent" || prev === "present" && state === "correct") {
          this.keyState[ch] = state;
          const keyEl = [...document.querySelectorAll('.key')].find(k => k.dataset.key === ch);
          if (keyEl) {
            keyEl.classList.remove("absent", "present", "correct");
            keyEl.classList.add(state);
          }
        }
      }

      if (guess === this.solution) {
        this.gameOver = true;
        this.showMessage("Đoán đúng rồi!", 5000, "win");
      } else if (++this.curRow >= this.ROWS) {
        this.gameOver = true;
        this.showMessage(`Thua! Đáp án: ${this.solution}`, 4000, "lose");
      } else {
        this.curCol = 0;
      }
    });
  }

  revealRow(r, guessArr, resultArr) {
    const version = this.gameVersion;
    return new Promise((resolve) => {
      for (let i = 0; i < this.COLS; i++) {
        setTimeout(() => {
          if (this.gameVersion !== version) return;
          const tile = this.boardEl.querySelector(`.tile[data-r="${r}"][data-c="${i}"]`);
          tile.classList.add("revealed", resultArr[i]);
          if (tile) {
          tile.classList.add("revealed", resultArr[i]);
        }

        if (i === this.COLS - 1) resolve();

      }, i * 250);
    }
  });
}

  showMessage(text, time = 1500, cls = "") {
    this.msgEl.textContent = text;
    this.msgEl.className = cls;
    if (time > 0) setTimeout(() => {
      this.msgEl.textContent = "";
      this.msgEl.className = "";
    }, time);
  }

}
window.GameWordle = GameWordle;